const types = {
    CREATE_TODO:'CREATE_TODO',
    UPDATE_TODO:'UPDATE_TODO',
    SET_TODO_EDIT:'SET_TODO_EDIT',
    DELETE_TODO:'DELETE_TODO',
    GET_TODOS:'GET_TODOS',
    TODO_TOOGLE_COMPLETED:'TODO_TOOGLE_COMPLETED'
};
export default types;